//! Codebooks for the IQ family, embedded straight from binary files so they cost no
//! source parsing time and no heap. Generated by tools/gen_quant_tables.py.

pub const ksigns_iq2xs: *const [128]u8 = @ptrCast(@embedFile("tables/ksigns_iq2xs.bin"));
pub const iq2xxs_grid: *const [256][8]u8 = @ptrCast(@embedFile("tables/iq2xxs_grid.bin"));
pub const iq2xs_grid: *const [512][8]u8 = @ptrCast(@embedFile("tables/iq2xs_grid.bin"));
pub const iq2s_grid: *const [1024][8]u8 = @ptrCast(@embedFile("tables/iq2s_grid.bin"));
pub const iq3xxs_grid: *const [256][4]u8 = @ptrCast(@embedFile("tables/iq3xxs_grid.bin"));
pub const iq3s_grid: *const [512][4]u8 = @ptrCast(@embedFile("tables/iq3s_grid.bin"));
pub const iq1s_grid: *const [2048][8]i8 = @ptrCast(@embedFile("tables/iq1s_grid.bin"));

/// 4 bit non linear codebook shared by IQ4_NL and IQ4_XS.
pub const kvalues_iq4nl: [16]i8 = .{ -127, -104, -83, -65, -49, -35, -22, -10, 1, 13, 25, 38, 53, 69, 89, 113 };

/// FP4 (E2M1) values stored doubled so they stay integers; the block scale carries the half.
pub const kvalues_fp4: [16]i8 = .{ 0, 1, 2, 3, 4, 6, 8, 12, 0, -1, -2, -3, -4, -6, -8, -12 };

pub const iq1s_delta: f32 = 0.125;

/// Sign bit masks used to expand a sign byte into eight signs.
pub const kmask_iq2xs: [8]u8 = .{ 1, 2, 4, 8, 16, 32, 64, 128 };
